spring:
  profiles: production
  data:
    mongodb:
      host: mongo # the db host
      port: 27017 # the connection port (defaults to 27107)
      uri: mongodb://mongo/production # connection URL
      database: production
      repositories.enabled: true # if spring data repository support is enabled