
spring:
  profiles: development
  data:
    rest:
      basePath: / #root URI for Spring Data REST
      defaultPageSize: 20 #change default number of items served in a single page
      maxPageSize: 100 #change maximum number of items in a single page
      #pageParamName: #change name of the query parameter for selecting pages
      #limitParamName: #change name of the query parameter for number of items to show in a page
      #sortParamName: #change name of the query parameter for sorting
      #defaultMediaType: #change default media type to use when none is specified
      returnBodyOnCreate: false #change if a body should be returned on creating a new entity
      returnBodyOnupdate: false #change if a body should be returned on updating an entity
  

    mongodb:
        host: localhost # the db host
        port: 27017 # the connection port (defaults to 27107)
        uri: localhost://mongodb/java-evaluation-service-test # connection URL
        database: development
        #authentication-database:
        #grid-fs-database:
        #username: test
        #password: test
        #repositories.enabled: true # if spring data repository support is enabled


---

spring:
  profiles: test
  data:
    rest:
      basePath: / #root URI for Spring Data REST
      defaultPageSize: 20 #change default number of items served in a single page
      maxPageSize: 100 #change maximum number of items in a single page
      #pageParamName: #change name of the query parameter for selecting pages
      #limitParamName: #change name of the query parameter for number of items to show in a page
      #sortParamName: #change name of the query parameter for sorting
      #defaultMediaType: #change default media type to use when none is specified
      returnBodyOnCreate: false #change if a body should be returned on creating a new entity
      returnBodyOnupdate: false #change if a body should be returned on updating an entity

    mongodb:
      host: mongo # the db host
      port: 27017 # the connection port (defaults to 27107)
      uri: mongodb://mongo/java-evaluation-service-test # connection URL
      database: test
      #authentication-database:
      #grid-fs-database:
      #username: test
      #password: test
      repositories.enabled: true # if spring data repository support is enabled


  


---

spring:
  profiles: production
  data:
    rest:
      basePath: / #root URI for Spring Data REST
      defaultPageSize: 20 #change default number of items served in a single page
      maxPageSize: 100 #change maximum number of items in a single page
      #pageParamName: #change name of the query parameter for selecting pages
      #limitParamName: #change name of the query parameter for number of items to show in a page
      #sortParamName: #change name of the query parameter for sorting
      #defaultMediaType: #change default media type to use when none is specified
      returnBodyOnCreate: false #change if a body should be returned on creating a new entity
      returnBodyOnupdate: false #change if a body should be returned on updating an entity
  

    mongodb:
      host: localhost # the db host
      port: 27017 # the connection port (defaults to 27107)
      uri: mongodb://localhost/production # connection URL
      database: production
      #authentication-database:
      #grid-fs-database:
      username: production
      password: production
      repositories.enabled: true # if spring data repository support is enabled


  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/